[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = ["npm install", "npx prisma generate"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npx prisma db push --accept-data-loss --skip-generate && node dist/server.js"
